//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundWaveOfficial
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoundWaveOfficialEntities1 : DbContext
    {
        public SoundWaveOfficialEntities1()
            : base("name=SoundWaveOfficialEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Podcast> tbl_Podcast { get; set; }
        public virtual DbSet<tbl_Registration1> tbl_Registration1 { get; set; }
    }
}
