//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundWaveOfficial
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Podcast
    {
        public int PodcastId { get; set; }
        public string PodcastName { get; set; }
        public string AuthorName { get; set; }
        public string Category { get; set; }
        public int UserId { get; set; }
        public string UploadFile { get; set; }
    
        public virtual tbl_Registration1 tbl_Registration1 { get; set; }
    }
}
